language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install vcrpy
  - pip install coveralls
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source hubblepy -m py.test
  - coverage report
after_success:
  coveralls